{% set version = "0.3.9.0" %}
{% set postf1 = "a" %}
{% set postf2 = "a" %}
{% set pandoc = "2.11" %}
{% set pandoc1 = "2.12" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ postf1 }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-Linux.tar.xz  # [linux64]
  sha256: aefb4b78d9524f93564ce5ba7e244fad6f90540a8ec035ffa80377eb55720441  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-macOS.tar.xz  # [osx]
  sha256: 207fff0ac71add057b6d9528dd9c7cd5511c9d827924dd29f0775a5e71b8d400  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-Windows.7z  # [win]
  sha256: b17ce7b5f07ba763c1739085f9b054027f2b98ea36ea5840b521c73b8bf1303f  # [win]

build:
  number: 0

requirements:
  run:
    - pandoc >={{ pandoc }},<{{ pandoc1 }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0-only
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Pandoc filter for cross-references
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
