{% set version = "0.3.23" %}
# this appears in version but not in url
{% set version_part = "" %}
# see https://github.com/lierdakil/pandoc-crossref/issues/311#issuecomment-844626176 for why there's a hidden part not normally seen in the version
{% set version_hidden_part = "a" %}
# best place to check the version constraint is https://hackage.haskell.org/package/pandoc-crossref
{% set pandoc_min_version = "3.8.2" %}
{% set pandoc_max_version = "3.9" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ version_part }}

# you may use VERSION=... sha256sum.sh to produce the following checksum
source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-Linux-X64.tar.xz  # [linux64]
  sha256: fa77e4e271547a97f0e29fd305b6674958a540d79f2a14a3b0ce9d6a6dc9de84  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-macOS-ARM64.tar.xz  # [osx and arm64]
  sha256: 96f6b59c2fd8bcf53a5dc1db73d63d218a5c40cb9c7008e884cc44596013ddd3  # [osx and arm64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-macOS-X64.tar.xz  # [osx and not arm64]
  sha256: 41cac35164fbc20a6582434a647b35b73321c3fcb2fce56503649ef461505035  # [osx and not arm64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-Windows-X64.7z  # [win]
  sha256: b4d4b795c665e0ec1592c0cee3d0ec13d1608d452fd39fbe99f002df3485c5b6  # [win]

build:
  number: 0

requirements:
  run:
    - pandoc >={{ pandoc_min_version }},<{{ pandoc_max_version }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref/
  # see https://github.com/lierdakil/pandoc-crossref#license
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Pandoc filter for cross-references
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://hackage.haskell.org/package/pandoc-crossref/

extra:
  recipe-maintainers:
    - kiwi0fruit
    - mfansler
    - knaaptime
    - ickc
