{% set version = "0.3.24" %}
# this appears in version but not in url
{% set version_part = "" %}
# see https://github.com/lierdakil/pandoc-crossref/issues/311#issuecomment-844626176 for why there's a hidden part not normally seen in the version
{% set version_hidden_part = "a" %}
# best place to check the version constraint is https://hackage.haskell.org/package/pandoc-crossref
{% set pandoc_min_version = "3.8.2" %}
{% set pandoc_max_version = "3.10" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ version_part }}

# you may use VERSION=... sha256sum.sh to produce the following checksum
source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-Linux-X64.tar.xz  # [linux64]
  sha256: afaa8867ab8d908b7e5ad1b96f62eedea6a5d3e89ee14e152cd72e67f535a728  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-macOS-ARM64.tar.xz  # [osx and arm64]
  sha256: de1b74b889a4c8063ae73ec72b7ade35b5b10d2f764ca218bfb4e178e6716a1b  # [osx and arm64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-macOS-X64.tar.xz  # [osx and not arm64]
  sha256: 3e46ee9becdd089cb1f6ebb13d784b25199adb8f2913aabaf7bc46f3256e5582  # [osx and not arm64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-Windows-X64.7z  # [win]
  sha256: 0c31ba7be945e8357e210873d178e7753cc5af462c96fa6051a86f5f12264d2a  # [win]

build:
  number: 0

requirements:
  run:
    - pandoc >={{ pandoc_min_version }},<{{ pandoc_max_version }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref/
  # see https://github.com/lierdakil/pandoc-crossref#license
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Pandoc filter for cross-references
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://hackage.haskell.org/package/pandoc-crossref/

extra:
  recipe-maintainers:
    - kiwi0fruit
    - mfansler
    - knaaptime
    - ickc
