{% set version = "0.3.25" %}
# this appears in version but not in url
{% set version_part = "" %}
# see https://github.com/lierdakil/pandoc-crossref/issues/311#issuecomment-844626176 for why there's a hidden part not normally seen in the version
{% set version_hidden_part = "a" %}
# best place to check the version constraint is https://hackage.haskell.org/package/pandoc-crossref
{% set pandoc_min_version = "3.8.2" %}
{% set pandoc_max_version = "3.10" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ version_part }}

# you may use VERSION=... sha256sum.sh to produce the following checksum
source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-Linux-X64.tar.xz  # [linux64]
  sha256: 7f8b7c5c91233db2dcb1145fa580a9ee8343695589bdb0ece8661490bc12a644  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-macOS-ARM64.tar.xz  # [osx and arm64]
  sha256: ce3571bd8bc335fa26bea46b390381a61bdf464bbf83fe4c7277160ba124a6fa  # [osx and arm64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-macOS-X64.tar.xz  # [osx and not arm64]
  sha256: 03e84e3fd03beb2b36ac2ed5bc2608825d759f33e657bec05af8be8b16ca7690  # [osx and not arm64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-Windows-X64.7z  # [win]
  sha256: ec2c1e5f14d118925c1357ba7f8c2bd5f04ad49efafd2d2181667494f9f4bddb  # [win]

build:
  number: 0

requirements:
  run:
    - pandoc >={{ pandoc_min_version }},<{{ pandoc_max_version }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref/
  # see https://github.com/lierdakil/pandoc-crossref#license
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Pandoc filter for cross-references
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://hackage.haskell.org/package/pandoc-crossref/

extra:
  recipe-maintainers:
    - kiwi0fruit
    - mfansler
    - knaaptime
    - ickc
