{% set version = "0.3.13.0" %}
# this appears in version but not in url
{% set version_part = "" %}
# see https://github.com/lierdakil/pandoc-crossref/issues/311#issuecomment-844626176 for why there's a hidden part not normally seen in the version
{% set version_hidden_part = "" %}
# best place to check the version constraint is https://hackage.haskell.org/package/pandoc-crossref
{% set pandoc_min_version = "2.18" %}
{% set pandoc_max_version = "2.19" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ version_part }}

# you may use VERSION=... sha256sum.sh to produce the following checksum
source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-Linux.tar.xz  # [linux64]
  sha256: 69ab1a4b2bbd956b8a7aaa0c2b2342a0ee4968e5848fe32c081a40f7efd42d98  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-macOS.tar.xz  # [osx]
  sha256: 544cbc5bbeebec64004f8cc8628fea8b53bff7914a53d4dda981233fd9082592  # [osx]
  
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-macOS.tar.xz  # [osx-arm64]
  sha256: 544cbc5bbeebec64004f8cc8628fea8b53bff7914a53d4dda981233fd9082592  # [osx-arm64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-Windows.7z  # [win]
  sha256: a3a8a51e226c9671b0938844db9e4c604277b7377aacfbc8000cf9560260eebd  # [win]

build:
  number: 1

requirements:
  run:
    - pandoc >={{ pandoc_min_version }},<{{ pandoc_max_version }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref/
  # see https://github.com/lierdakil/pandoc-crossref#license
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Pandoc filter for cross-references
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://hackage.haskell.org/package/pandoc-crossref/

extra:
  recipe-maintainers:
    - kiwi0fruit
    - mfansler
    - knaaptime
    - ickc
